#
# Copyright 2026 The OKDP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# you may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

# This is to override the chart name.
nameOverride: ""
fullnameOverride: "opa"

replicaCount: 1

image: openpolicyagent/opa:1.13.2

opaArgs:
  - "run"
  - "--server"
  - "--addr=0.0.0.0:8443"
  - "--log-format=json-pretty"
  - "--set=status.console=true"
  - "--set=decision_logs.console=true"
  # - "--tls-cert-file=/certs/tls.crt"
  # - "--tls-private-key-file=/certs/tls.key"
  # - "--config-file=/config/config.yaml"

# env:
#   - name: AWS_ACCESS_KEY_ID
#     value: snu8yoP6QAlY0ne4
#   - name: AWS_SECRET_ACCESS_KEY
#     value: PNzBcmeLNEdR0oviwm04NQAicOrDH1Km
#   - name: AWS_REGION
#     value: us-east-1

readinessProbe:
  httpGet:
    path: "/health?plugins&bundle"
    # Put HTTPS if certificate is added
    scheme: HTTP
    port: 8443
  initialDelaySeconds: 3
  periodSeconds: 10
livenessProbe:
  httpGet:
    path: "/health"
    # Put HTTPS if certificate is added
    scheme: HTTP
    port: 8443
  initialDelaySeconds: 3
  periodSeconds: 10

# volumes:
#   # Volume containing configration
#   configVolume:
#     name: config
#     configMapName: opa-config
#     mountPath: /config
#   # Volume containing TLS certificat
#   tlsVolume:
#     name: certs
#     secretName: opa-tls-secret
#     mountPath: /certs

service:
  type: ClusterIP
  port: 443
  targetPort: 8443

# Volume for TLS must be defined
certificate:
  enabled: false
  dnsNames:
  - opa.opa-ns

# Volume for config must be defined
# Can be used if an OPA bundle is located in SeaweedFS
config:
  enabled: false
  data: |
    services:
      seaweedfs:
        url: https://seaweedfs-seaweedfs-default.okdp.sandbox
        allow_insecure_tls: true
        credentials:
          s3_signing:
            environment_credentials: {}

    bundles:
      mybundle:
        service: seaweedfs
        resource: trino/opa/bundle.tar.gz
        polling:
          min_delay_seconds: 10
          max_delay_seconds: 20
